//! Sortie types — the unit of work oracle uploads to legion in one frame and
//! advances step by step via the [`OracleToLegion::Proceed`] handshake.
//!
//! Both oracle and legion share these types verbatim through this crate.
//!
//! [`OracleToLegion::Proceed`]: crate::messages::OracleToLegion::Proceed

use alloc::string::String;
use alloc::vec::Vec;
use serde::{Deserialize, Serialize};

/// Identifier for a drone (e.g. `"drone-01"`). Carried in [`Envelope`] for
/// routing on a shared serial radio channel where multiple drones coexist.
///
/// [`Envelope`]: crate::messages::Envelope
pub type DroneId = String;

/// Identifier for a [`HivemindPlan`]. Generated by oracle as a uuid v7 string.
///
/// [`HivemindPlan`]: ../../../oracle/README.md
pub type PlanId = String;

/// Identifier for a [`Sortie`]. Generated by oracle as part of plan creation.
pub type SortieId = String;

/// A complete, self-contained per-drone sortie. Oracle uploads one of these
/// to legion in a single frame; legion stores it locally and executes it step
/// by step under oracle's `Proceed` gating.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Sortie {
    pub sortie_id: SortieId,
    pub plan_id: PlanId,
    pub drone_id: DroneId,
    pub steps: Vec<SortieStep>,
    pub paint_volume_ml: f32,
    pub expected_duration_s: u32,
}

/// A single step within a [`Sortie`]. Legion advances through these in order,
/// blocking on `Proceed` from oracle between every step (or falling back to
/// the per-step [`RadioLossPolicy`] if oracle goes silent mid-step).
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct SortieStep {
    /// 0-based, monotonic within the sortie. Used as the gating key in
    /// `Proceed { expected_step_index }`.
    pub index: u32,
    pub step_type: StepType,
    /// Destination waypoint (or starting waypoint for path-following steps).
    pub waypoint: Waypoint,
    /// For `SprayPass` and multi-waypoint `Transit` segments, the full path.
    /// `None` for single-waypoint steps.
    pub path: Option<Vec<Waypoint>>,
    pub speed_m_s: f32,
    /// Whether the spray pump should be on for the duration of this step.
    pub spray: bool,
    pub radio_loss: RadioLossPolicy,
    /// Wall-clock budget the slicer estimated for this step. Used by legion's
    /// executor as a watchdog.
    pub expected_duration_s: u32,
}

/// The kind of work a [`SortieStep`] represents. Each variant maps to a
/// specific handler in legion's executor.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
pub enum StepType {
    Takeoff,
    Transit,
    SprayPass,
    RefillApproach,
    RefillWait,
    ReturnToBase,
    Land,
}

/// A 3D point with optional yaw, used both as flight targets in steps and as
/// path vertices in spray passes.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq)]
pub struct Waypoint {
    pub lat: f64,
    pub lon: f64,
    pub alt_m: f32,
    /// Desired yaw at this point, if any. `None` means "don't constrain yaw."
    pub yaw_deg: Option<f32>,
}

/// What legion should do if oracle goes silent during this step. Stamped on
/// every step at slice time. The slicer picks defaults per `StepType` and the
/// operator can override.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct RadioLossPolicy {
    pub behaviour: RadioLossBehaviour,
    /// How long without contact (no heartbeat or command) before legion
    /// considers oracle silent and trips the policy.
    pub silent_timeout_s: f32,
    /// For [`RadioLossBehaviour::HoldThenRtl`]: how long to hold position
    /// after `silent_timeout_s` before initiating RTL.
    pub hold_then_rtl_after_s: Option<f32>,
}

/// The three policy outcomes legion supports.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
pub enum RadioLossBehaviour {
    /// Finish the current step autonomously, then hold at the destination.
    Continue,
    /// Hold position immediately; if oracle is still silent after
    /// `hold_then_rtl_after_s`, RTL.
    HoldThenRtl,
    /// Don't wait — RTL right away.
    RtlImmediately,
}

/// Sortie progress carried in `LegionToOracle::Hello` when legion boots with
/// a partially-completed sortie persisted to disk.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct InProgressSortie {
    pub sortie_id: SortieId,
    /// The highest step index legion successfully completed before the
    /// interruption, or `None` if no steps had been gated yet.
    pub last_completed_step: Option<u32>,
}
